### ISSUE TITLE
Great post

### ISSUE THREAD

**Issue by theJiawen** [Monsoir/Notes#1]
it helps a lot ! 
谢谢，嘻嘻

**Comment by theJiawen** [comment]
我指这篇：
https://github.com/Monsoir/Notes/blob/master/Visual%20Studio%20Code/Visual%20Studio%20Code%20%E4%B8%AD%E8%B0%83%E8%AF%95%E4%BD%BF%E7%94%A8%20ES6%20%E7%89%B9%E6%80%A7%E7%9A%84%20Node.js.md#visual-studio-code-%E4%B8%AD%E8%B0%83%E8%AF%95%E4%BD%BF%E7%94%A8-es6-%E7%89%B9%E6%80%A7%E7%9A%84-nodejs

**Comment by monsoir** [comment]
Glad it helps, thanks for letting me know!
