### ISSUE TITLE
楼主，有个地方需要更新下

### ISSUE THREAD

**Issue by dkvirus** [Monsoir/Notes#2]
参照这篇文章 [Visual Studio Code 中调试使用 ES6 特性的 Node.js](https://github.com/Monsoir/Notes/blob/master/Visual%20Studio%20Code/debug-es6-in-vscode.md) 介绍的步骤一步步来的，发现并不能调试 src 下面的代码。

后来发现使用 babel 编译时加上 source-map 选项后才能调试 src 下源码了，maybe babel 更新导致我测试与楼主当时测试的差异化，希望楼主能更新一下。修改 package.json 中 scripts 脚本。

```
"build": "babel ./src -d ./build --source-maps",
"start": "npm run build && node ./build/index.js",
```

另外，这篇帖子对我的帮助真的很大👍👍，github 上有很多项目都在用 es6 语法写 node 程序，一直搞不懂这些人是如何调试的，想看源码也无从下嘴，找万能的谷歌也不知道查询关键字填啥合适。问下这篇文章能否转载一下，会注明原文作者及地址，希望让更多需要的人看到。

**Comment by monsoir** [comment]
1. 谢谢你的指正！错误的地方已经修改好了。
2. 可以转载的，谢谢！
3. 同时针对 Node v10.11.0, VSCode Version 1.30.1 进行了更新。
